### ISSUE TITLE
Published drafts should be organized by publish date, not draft creation date

### ISSUE THREAD

**Issue by julietdaniel** [VenusInterns/BlogTemplate#121]
Repro:
1. Write a post called "Published later." Save it as a draft.
2. Write a post called "Published now." Publish it.
3. Now go to the edit page for "Published later" and publish the post.
4. View the Index page.

Actual: "Published later" is listed below "Published now" as if it had been published at an earlier date than "Published now," which was in fact published first, although it was created second.
Expected: "Published later" should show up as a more recent post than "Published now." Published drafts should be listed on the Index page according to the date that they were published, not the date that they were saved as a draft.

**Comment by julietdaniel** [comment]
This will require making changes to the OnPostPublish method in Edit.cshtml.cs. This file has been heavily revamped due to the ViewModels refactoring (PR #93), so address this issue after that PR is merged.

**Comment by lucasisaza** [comment]
When we were first figuring out how to order posts we talked about this, the way it should work is the following:

If you...

- Publish then save then publish -> We use the first publish date and never change it again
- Save then publish -> We again want to use the first publish date and never change it again 

The second is the issue the one going on here and I'm pretty sure its happening because in the Post.cs Model we automatically set the PubDate as DateTimeOffset and when we publish from the Edit page we do not check or have a way of checking whether the post has been published in the past (i.e. scenario 1) or not so essentially the date isn't changed and the post uses the date that it was assigned when it was first saved. To mitigate this issue we need to explicitly set the date in the publish method and if the date doesn't get set it will revert to 0001/1/1 12:00 am +00:00 so we can check if this is the date than the post has never been published.

**Comment by umaslakshmi** [comment]
@julietdaniel I think you took out the code that took care of this in one of your pull requests, #93. It was lines 67-77 in Edit.cshtml.cs.

**Comment by julietdaniel** [comment]
Fixed in PR #93
